### ISSUE TITLE
RaspberryPi4 with DietPi

### ISSUE THREAD

**Issue by hotmtk** [godver3/cli_debrid#294]
root@DietPi:/opt/cli_debrid# docker compose up -d
[+] Running 0/1
 ⠦ cli_debrid Pulling                                                                                                                                   1.7s
no matching manifest for linux/arm64/v8 in the manifest list entries
root@DietPi:/opt/cli_debrid#

There is no arm64 version to download:
https://raw.githubusercontent.com/godver3/cli_debrid/main_arm64/docker-compose.yml
404: Not Found

**Comment by godver3** [comment]
Hi there - for arm64 you'll need to adjust your docker-compose.yml a bit:

```
services:
  cli_debrid:
    image: godver3/cli_debrid:dev-arm64
    pull_policy: always
    container_name: cli_debrid
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /host/location/db_content:/user/db_content
      - /host/location/config:/user/config
      - /host/location/logs:/user/logs
      - /media/mount:/media/mount # optional - used by video player
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true
```
